<?php

namespace Container7lynQae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AhTbvtwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ahTbvtw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ahTbvtw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentairesRepository' => ['privates', 'App\\Repository\\CommentairesRepository', 'getCommentairesRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repository' => ['privates', 'App\\Repository\\ArticlesRepository', 'getArticlesRepositoryService', true],
        ], [
            'commentairesRepository' => 'App\\Repository\\CommentairesRepository',
            'manager' => '?',
            'repository' => 'App\\Repository\\ArticlesRepository',
        ]);
    }
}
