<?php

namespace Container7lynQae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticlesRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ArticlesRepository' shared autowired service.
     *
     * @return \App\Repository\ArticlesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ArticlesRepository'] = new \App\Repository\ArticlesRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
