<?php

namespace ContainerRLb3mOO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zo94LdmService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Zo94Ldm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zo94Ldm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator.Zo94Ldm.App\\Entity\\Articles', NULL, 'Cannot autowire service ".service_locator.Zo94Ldm": it references class "App\\Entity\\Articles" but no such service exists.'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'article' => 'App\\Entity\\Articles',
            'manager' => '?',
        ]);
    }
}
