<?php

namespace ContainerIUXvZIe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CodPIhDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.codPIhD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.codPIhD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::addArticle' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\AdminController::deleteArticles' => ['privates', '.service_locator.Zo94Ldm', 'get_ServiceLocator_Zo94LdmService', true],
            'App\\Controller\\AdminController::listAll' => ['privates', '.service_locator.bbU9gLy', 'get_ServiceLocator_BbU9gLyService', true],
            'App\\Controller\\AdminController::updateArticle' => ['privates', '.service_locator.Zo94Ldm', 'get_ServiceLocator_Zo94LdmService', true],
            'App\\Controller\\CategoriesController::addCategorie' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\MainController::detail' => ['privates', '.service_locator.ahTbvtw', 'get_ServiceLocator_AhTbvtwService', true],
            'App\\Controller\\MainController::index' => ['privates', '.service_locator.bbU9gLy', 'get_ServiceLocator_BbU9gLyService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController::register' => ['privates', '.service_locator.hdrCzai', 'get_ServiceLocator_HdrCzaiService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdminController:addArticle' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\AdminController:deleteArticles' => ['privates', '.service_locator.Zo94Ldm', 'get_ServiceLocator_Zo94LdmService', true],
            'App\\Controller\\AdminController:listAll' => ['privates', '.service_locator.bbU9gLy', 'get_ServiceLocator_BbU9gLyService', true],
            'App\\Controller\\AdminController:updateArticle' => ['privates', '.service_locator.Zo94Ldm', 'get_ServiceLocator_Zo94LdmService', true],
            'App\\Controller\\CategoriesController:addCategorie' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\MainController:detail' => ['privates', '.service_locator.ahTbvtw', 'get_ServiceLocator_AhTbvtwService', true],
            'App\\Controller\\MainController:index' => ['privates', '.service_locator.bbU9gLy', 'get_ServiceLocator_BbU9gLyService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController:register' => ['privates', '.service_locator.hdrCzai', 'get_ServiceLocator_HdrCzaiService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdminController::addArticle' => '?',
            'App\\Controller\\AdminController::deleteArticles' => '?',
            'App\\Controller\\AdminController::listAll' => '?',
            'App\\Controller\\AdminController::updateArticle' => '?',
            'App\\Controller\\CategoriesController::addCategorie' => '?',
            'App\\Controller\\MainController::detail' => '?',
            'App\\Controller\\MainController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:addArticle' => '?',
            'App\\Controller\\AdminController:deleteArticles' => '?',
            'App\\Controller\\AdminController:listAll' => '?',
            'App\\Controller\\AdminController:updateArticle' => '?',
            'App\\Controller\\CategoriesController:addCategorie' => '?',
            'App\\Controller\\MainController:detail' => '?',
            'App\\Controller\\MainController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
