<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRLb3mOO\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRLb3mOO/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRLb3mOO.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRLb3mOO\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerRLb3mOO\App_KernelProdContainer([
    'container.build_hash' => 'RLb3mOO',
    'container.build_id' => '45c95110',
    'container.build_time' => 1648714987,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRLb3mOO');
