<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL3RRxk3\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL3RRxk3/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerL3RRxk3.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerL3RRxk3\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerL3RRxk3\App_KernelProdContainer([
    'container.build_hash' => 'L3RRxk3',
    'container.build_id' => '03ccc7c0',
    'container.build_time' => 1649160742,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL3RRxk3');
