<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin_list' => [[], ['_controller' => 'App\\Controller\\AdminController::listAll'], [], [['text', '/admin/list']], [], []],
    'admin_new' => [[], ['_controller' => 'App\\Controller\\AdminController::addArticle'], [], [['text', '/admin/new']], [], []],
    'admin_update' => [['id'], ['_controller' => 'App\\Controller\\AdminController::updateArticle'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/update']], [], []],
    'admin_delete' => [['id'], ['_controller' => 'App\\Controller\\AdminController::deleteArticles'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/delete']], [], []],
    'categorie_new' => [[], ['_controller' => 'App\\Controller\\CategoriesController::addCategorie'], [], [['text', '/admin/categorie/new']], [], []],
    'main_home' => [[], ['_controller' => 'App\\Controller\\MainController::index'], [], [['text', '/']], [], []],
    'detail' => [['id'], ['_controller' => 'App\\Controller\\MainController::detail'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/detail']], [], []],
    'mentions' => [[], ['_controller' => 'App\\Controller\\MainController::mentions'], [], [['text', '/mentions']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/ginlo']], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'user_register' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/register030578']], [], []],
];
