<?php

namespace ContainerXFQQX2m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A8YmG9KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a8YmG9K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a8YmG9K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repository' => ['privates', 'App\\Repository\\ArticlesRepository', 'getArticlesRepositoryService', true],
        ], [
            'manager' => '?',
            'repository' => 'App\\Repository\\ArticlesRepository',
        ]);
    }
}
