<?php

namespace ContainerXFQQX2m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EoOi_WEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eoOi.wE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eoOi.wE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentairesRepo' => ['privates', 'App\\Repository\\CommentairesRepository', 'getCommentairesRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\ArticlesRepository', 'getArticlesRepositoryService', true],
        ], [
            'commentairesRepo' => 'App\\Repository\\CommentairesRepository',
            'repository' => 'App\\Repository\\ArticlesRepository',
        ]);
    }
}
