<?php

namespace ContainerXFQQX2m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaireFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CommentaireFormType' shared autowired service.
     *
     * @return \App\Form\CommentaireFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CommentaireFormType'] = new \App\Form\CommentaireFormType();
    }
}
