<?php

namespace ContainerXFQQX2m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentairesRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\CommentairesRepository' shared autowired service.
     *
     * @return \App\Repository\CommentairesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CommentairesRepository'] = new \App\Repository\CommentairesRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
