<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7VMkfUq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7VMkfUq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7VMkfUq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7VMkfUq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7VMkfUq\App_KernelDevDebugContainer([
    'container.build_hash' => '7VMkfUq',
    'container.build_id' => 'a77b7784',
    'container.build_time' => 1688464975,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7VMkfUq');
