<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP6EbRmA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP6EbRmA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP6EbRmA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP6EbRmA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP6EbRmA\App_KernelDevDebugContainer([
    'container.build_hash' => 'P6EbRmA',
    'container.build_id' => '282247ac',
    'container.build_time' => 1654540988,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP6EbRmA');
